### ISSUE TITLE
OpenCV error

### ISSUE THREAD

**Issue by anuj0456** [WebsiteBeaver/android-document-scanner#18]
I keep getting this error

java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.imgcodecs.Imgcodecs.imread_1(java.lang.String) (tried Java_org_opencv_imgcodecs_Imgcodecs_imread_11 and Java_org_opencv_imgcodecs_Imgcodecs_imread_11__Ljava_lang_String_2)
                                                                                                    	at org.opencv.imgcodecs.Imgcodecs.imread_1(Native Method)
                                                                                                    	at org.opencv.imgcodecs.Imgcodecs.imread(Imgcodecs.java:114)
                                                                                                    	at com.websitebeaver.documentscanner.utils.ImageUtil.getImageFromFilePath(ImageUtil.kt:34)
                                                                                                    	at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:98)
                                                                                                    	at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:84)
                                                                                                    	at com.websitebeaver.documentscanner.utils.CameraUtil.startForResult$lambda-0(CameraUtil.kt:41)
                                                                                                    	at com.websitebeaver.documentscanner.utils.CameraUtil.$r8$lambda$QtmUm3JcXlX2aa1YkJnrPoMUzS8(Unknown Source:0)
                                                                                                    	at com.websitebeaver.documentscanner.utils.CameraUtil$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
                                                                                                    	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:793)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8551)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5455)
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4904)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4950)
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8319)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

I tried custom updating the documentScanner module but still no luck.

**Comment by dmarcs** [comment]
try running the example in this repo

**Comment by alexglazkov9** [comment]
I can see this exact error happening fairly often in Crashlytics too. Using this library in React Native app as a part of `react-native-document-scanner-plugin`. Any ideas what can be causing it? Let me know if I can help to debug

**Comment by dmarcs** [comment]
I can't reproduce this issue, but I think https://github.com/WebsiteBeaver/android-document-scanner/pull/24 fixes it.

https://github.com/WebsiteBeaver/android-document-scanner/tree/1.3.3

load OpenCV in onCreate instead of onResume to avoid OpenCV not being loaded in time
