### ISSUE TITLE
OpenCV(4.1.0) Error: Assertion failed (!_src.empty()) in cvtColor,

### ISSUE THREAD

**Issue by mohammedhemaid** [WebsiteBeaver/android-document-scanner#21]
I tested the sample app on Pixel 2 XL Android 11 and I got this crash, however I tested it on pixel 5 Android 13 and it worked fine

A resource failed to call close. 
OpenCV(4.1.0) Error: Assertion failed (!_src.empty()) in cvtColor, file /build/master_pack-android/open
imgproc::cvtColor_11() caught cv::Exception: OpenCV(4.1.0) /build/master_pack-android/opencv/modules/im
Shutting down VM
FATAL EXCEPTION: main
Process: com.websitebeaver.documentscanner.demo, PID: 13595
java.lang.RuntimeException: Unable to resume activity {com.websitebeaver.documentscanner.demo/com.websi
]
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4444)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=953472882
]
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4431)
	... 11 more

**Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.0) /build/master_pack-an
]
	at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
	at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:2309)
	at com.websitebeaver.documentscanner.utils.ImageUtil.getImageFromFilePath(ImageUtil.kt:38)
	at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerAct
	at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerAct
	at com.websitebeaver.documentscanner.utils.CameraUtil.startForResult$lambda-0(CameraUtil.kt:41)
	at com.websitebeaver.documentscanner.utils.CameraUtil.$r8$lambda$QtmUm3JcXlX2aa1YkJnrPoMUzS8(Unknow
	at com.websitebeaver.documentscanner.utils.CameraUtil$$ExternalSyntheticLambda0.onActivityResult(Un
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:647)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:8310)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
	... 12 more**

**Comment by mohammedzipo** [comment]
After a lot of debugging I found that there is an issue in the file path in Android 11, I have tried different solution to get the file path from URI but it didn't work

**Comment by mohammedhemaid** [comment]
After I checked this on emulator Android 11, the app worked fine, seems there is an issue on my Pixel 2xl Android 11 device
